/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author chr97lubuntu
 */
public class rh extends javax.swing.JFrame {
    Conexion con = new Conexion();
    Connection Consulta = con.conexion();
     private String idUsuario="";
    /**
     * Creates new form rh
     */
       DefaultTableModel modelo = new DefaultTableModel() {
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
        };
    public rh() {
        initComponents();
                        this.setTitle("Recursos Humanos - Sistema Inventario BTZ");

        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE); 
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();    
 this.setLocationRelativeTo(null);        
      
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DPI");
        modelo.addColumn("Usuario");
        modelo.addColumn("Puesto");
        modelo.addColumn("Estado");
        emple.setModel(modelo);
        String datos[] = new String[6];
        try {

            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Nombre, Apellido, DPI, Usuario, Privilegios,Activo FROM Usuarios");
          
            while (Ca.next()) {
               
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(3);
                datos[3] = Ca.getString(4);
                datos[4] = Ca.getString(5);
                if(Ca.getString(6).equals("1"))
                {
                    datos[5]="Activo";
                }
                else
                {
                    datos[5]="De Baja";
                }
                
                             
                modelo.addRow(datos);
                
            }
            emple.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(rh.class.getName()).log(Level.SEVERE, null, ex);
        }
        emple.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addemple = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        emple = new javax.swing.JTable();
        regresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 111, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addemple.setBackground(new java.awt.Color(189, 189, 189));
        addemple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-agregar-administrador-100.png"))); // NOI18N
        addemple.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        addemple.setContentAreaFilled(false);
        addemple.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-agregar-administrador-filled-100.png"))); // NOI18N
        addemple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempleActionPerformed(evt);
            }
        });
        jPanel1.add(addemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 100));

        emple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(emple);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 730, 340));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-volver-asignación-50.png"))); // NOI18N
        regresar.setContentAreaFilled(false);
        regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-volver-asignación-filled-50.png"))); // NOI18N
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 50, -1));

        jButton1.setText("<html>EDITAR</html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 70));

        jButton2.setText("<html>DAR DE BAJA</html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 70));

        jButton3.setText("<html>DAR DE ALTA</html>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addempleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempleActionPerformed
        // TODO add your handling code here:
        agregaremple aem = new agregaremple();
        aem.setVisible(true);
        dispose();
    }//GEN-LAST:event_addempleActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here
        Menu men=new Menu();
        men.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_regresarActionPerformed
    private void actualizar()
    {
        modelo.setRowCount(0);
         String datos[] = new String[6];
        try {

            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT Nombre, Apellido, DPI, Usuario, Privilegios,Activo FROM Usuarios");
          
            while (Ca.next()) {
               
                datos[0] = Ca.getString(1);
                datos[1] = Ca.getString(2);
                datos[2] = Ca.getString(3);
                datos[3] = Ca.getString(4);
                datos[4] = Ca.getString(5);
                if(Ca.getString(6).equals("1"))
                {
                    datos[5]="Activo";
                }
                else
                {
                    datos[5]="De Baja";
                }
                
                             
                modelo.addRow(datos);
                
            }
            emple.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Menu x=new Menu();
        x.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
 private Boolean construir(){
        LoginView n=new LoginView(null,true);
        new LoginController(n);
        n.addWindowListener(new WindowAdapter(){
             @Override
             public void windowClosing(WindowEvent we )
             {
                 System.exit(0);
             }
        });
        n.pack();
        n.setLocationRelativeTo(null);
        
        n.setVisible(true);
        idUsuario=n.getRol();
        if(idUsuario.equals(""))
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    private void dardebaja()
    {
        try {
            PreparedStatement ActualizarProveedor = Consulta.prepareStatement("UPDATE "
                    + "Usuarios SET Activo=false where DPI='"+String.valueOf(emple.getValueAt(emple.getSelectedRow(), 2))+"'");
            ActualizarProveedor.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(rh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void dardealta()
    {
        try {
            PreparedStatement ActualizarProveedor = Consulta.prepareStatement("UPDATE "
                    + "Usuarios SET Activo=true where DPI='"+String.valueOf(emple.getValueAt(emple.getSelectedRow(), 2))+"'");
            ActualizarProveedor.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(rh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int seleccionar = 0;
        seleccionar = emple.getSelectedRow();
        if (seleccionar != -1) {
            if (construir()) {
                    dardebaja();
                    actualizar();
            } else {
                JOptionPane.showMessageDialog(null, "Acceso Denegado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Un Empleado");
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int seleccionar = 0;
        seleccionar = emple.getSelectedRow();
        if (seleccionar != -1) {
            if (construir()) {
                dardealta();
                actualizar();
            } else {
                JOptionPane.showMessageDialog(null, "Acceso Denegado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Un Empleado");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int seleccionar = 0;
        seleccionar = emple.getSelectedRow();
        if (seleccionar != -1) {
            if (construir()) {
                
            } else {
                JOptionPane.showMessageDialog(null, "Acceso Denegado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione Un Empleado");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemple;
    private javax.swing.JTable emple;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
