/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author chr97lubuntu
 */
public class verempleado extends javax.swing.JFrame {
    Conexion con = new Conexion();
    Connection cn = con.conexion();
    Connection tr = con.conexion();
    Connection us = con.conexion();
    boolean disponible =true;
        Connection Consulta = con.conexion();
      private  String idUsuario="";
        
    /**
     * Creates new form agregaremple
     */
    public verempleado(String id) {
        initComponents();
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocationRelativeTo(null);
        //  boxpuesto.addItem("Vendedor");
        // boxpuesto.addItem("Dueño");

        contraseña.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                contraseña.setText(null);

            }
        });

        cocontraseña.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                cocontraseña.setText(null);

            }
        });
        Diponible.setVisible(false);
        correcto.setVisible(false);
         dpiregis.setVisible(false);
        this.setTitle("Ingreso Empleados - Sistema Inventario BTZ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneldatos = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        dpi = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        boxpuesto = new javax.swing.JComboBox<>();
        Diponible = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        cocontraseña = new javax.swing.JPasswordField();
        correcto = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        dpiregis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(17, 111, 172));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneldatos.setBackground(new java.awt.Color(17, 111, 172));
        paneldatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        paneldatos.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 20, 338, -1));

        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        paneldatos.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 64, 338, -1));

        dpi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dpiFocusLost(evt);
            }
        });
        dpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dpiKeyTyped(evt);
            }
        });
        paneldatos.add(dpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 110, 175, -1));

        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });
        paneldatos.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 159, 135, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        paneldatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");
        paneldatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DPI");
        paneldatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario");
        paneldatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setText("Contraseña");
        paneldatos.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        paneldatos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 296, -1, -1));

        boxpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador","Vendedor" }));
        boxpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxpuestoActionPerformed(evt);
            }
        });
        paneldatos.add(boxpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 160, -1));

        Diponible.setText("Disponible");
        paneldatos.add(Diponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contraseña");
        paneldatos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñaKeyTyped(evt);
            }
        });
        paneldatos.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        cocontraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cocontraseñaFocusLost(evt);
            }
        });
        cocontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cocontraseñaKeyTyped(evt);
            }
        });
        paneldatos.add(cocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, -1));

        correcto.setText("Disponible");
        paneldatos.add(correcto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-guardar-como-100.png"))); // NOI18N
        guardar.setContentAreaFilled(false);
        guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoso/icons8-guardar-como-filled-100.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        paneldatos.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 115, -1));

        dpiregis.setText("jLabel3");
        paneldatos.add(dpiregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jPanel1.add(paneldatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 620, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private Boolean construir() {
        LoginView n = new LoginView(null, true);
        new LoginController(n);
        n.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                System.exit(0);
            }
        });
        n.pack();
        n.setLocationRelativeTo(null);

        n.setVisible(true);
        idUsuario = n.getRol();
        if (idUsuario.equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private Boolean DPIDis() {
        Boolean valor = true;
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT id from Usuarios where DPI='"+dpi.getText()+"'");
            while(Ca.next())
            {
                valor=false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(verempleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return valor;
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if(construir())
        {
            if (disponible==false || nombre.getText().equals("") || apellido.getText().equals("") || dpi.getText().equals("")
                || usuario.getText().equals("")|| contraseña.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Revise que todos los campos esten llenos");

            }
            else
            {
                if(Diponible.getText().equals("No Disponible")!=true&&correcto.getText().equals("No Coincide")!=true&&DPIDis()==true)
                {
                    try
                    {
                        PreparedStatement CrearEm = cn.prepareStatement("INSERT INTO Usuarios(Nombre,Apellido,Usuario,Contraseña,DPI,Privilegios) "
                            + "VALUES(?,?,?,?,?,?)");
                        CrearEm.setString(1, nombre.getText());
                        CrearEm.setString(2, apellido.getText());
                        CrearEm.setString(3,usuario.getText());
                        CrearEm.setString(4,contraseña.getText());
                        CrearEm.setString(5,dpi.getText());
                        CrearEm.setString(6,boxpuesto.getSelectedItem().toString());//puesto
                        CrearEm.executeUpdate();
                        CrearEm.close();
                        JOptionPane.showMessageDialog(null, "Nuevo empleado Agregado");
                    }
                    catch (SQLException ex)
                    {
                        Logger.getLogger(IngresarProve.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    rh x=new rh();
                    x.setVisible(true);
                    dispose();
                }
                else
                {
                    if(Diponible.getText().equals("No Disponible"))
                    {
                        JOptionPane.showMessageDialog(null, "Cambie de usuario");

                    }
                    if(correcto.getText().equals("No Coincide"))
                    {
                        JOptionPane.showMessageDialog(null, "Confirme su contraseña");

                    }

                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");

        }
    }//GEN-LAST:event_guardarActionPerformed

    private void cocontraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cocontraseñaFocusLost
        if(Dipo2())
        {
            if(contraseña.getText().equals("")||cocontraseña.getText().equals(""))
            {
                correcto.setVisible(true);
                correcto.setText("Confirme Su Contraseña");
            }
            else
            {
                correcto.setVisible(true);
                correcto.setText("Coincide");
            }
                 
            
        }
        else
        {
            correcto.setText("No Coincide");
            correcto.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cocontraseñaFocusLost

    private void boxpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxpuestoActionPerformed

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost

        if(Dipo())
        {
            
            if(usuario.getText().equals(""))
            {
                Diponible.setVisible(true);
                Diponible.setText("Ingrese Usuario");
            }
            else
            {
                Diponible.setVisible(true);
                Diponible.setText("Disponible");
            }
        }
        
        else
        {
            Diponible.setText("No Disponible");
            Diponible.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            rh r=new rh();
            r.setVisible(true);
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void dpiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dpiFocusLost
        if(DPIDis()==false)
        {
            dpiregis.setVisible(true);
            dpiregis.setText("DPI ya registrado");
        }
        else
        {
            dpiregis.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dpiFocusLost

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        int k = (int) evt.getKeyChar();
        if (k == 10) {
            apellido.requestFocus();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped
int k = (int) evt.getKeyChar();
        if (k == 10) {
            dpi.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoKeyTyped

    private void dpiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpiKeyTyped
int k = (int) evt.getKeyChar();
        if (k == 10) {
            usuario.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dpiKeyTyped

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
int k = (int) evt.getKeyChar();
        if (k == 10) {
            contraseña.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyTyped

    private void contraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaKeyTyped
int k = (int) evt.getKeyChar();
        if (k == 10) {
            cocontraseña.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaKeyTyped

    private void cocontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cocontraseñaKeyTyped
        int k = (int) evt.getKeyChar();
        if (k == 10) {
              if(construir())
        {
            if (disponible==false || nombre.getText().equals("") || apellido.getText().equals("") || dpi.getText().equals("")
                || usuario.getText().equals("")|| contraseña.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Revise que todos los campos esten llenos");

            }
            else
            {
                if(Diponible.getText().equals("No Disponible")!=true&&correcto.getText().equals("No Coincide")!=true&&DPIDis()==true)
                {
                    try
                    {
                        PreparedStatement CrearEm = cn.prepareStatement("INSERT INTO Usuarios(Nombre,Apellido,Usuario,Contraseña,DPI,Privilegios) "
                            + "VALUES(?,?,?,?,?,?)");
                        CrearEm.setString(1, nombre.getText());
                        CrearEm.setString(2, apellido.getText());
                        CrearEm.setString(3,usuario.getText());
                        CrearEm.setString(4,contraseña.getText());
                        CrearEm.setString(5,dpi.getText());
                        CrearEm.setString(6,boxpuesto.getSelectedItem().toString());//puesto
                        CrearEm.executeUpdate();
                        CrearEm.close();
                        JOptionPane.showMessageDialog(null, "Nuevo empleado Agregado");
                    }
                    catch (SQLException ex)
                    {
                        Logger.getLogger(IngresarProve.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    rh x=new rh();
                    x.setVisible(true);
                    dispose();
                }
                else
                {
                    if(Diponible.getText().equals("No Disponible"))
                    {
                        JOptionPane.showMessageDialog(null, "Cambie de usuario");

                    }
                    if(correcto.getText().equals("No Coincide"))
                    {
                        JOptionPane.showMessageDialog(null, "Confirme su contraseña");

                    }

                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");

        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cocontraseñaKeyTyped
        
        
        private Boolean Dipo2()
    {
        if(contraseña.getText().equals(cocontraseña.getText()))
        {
            return true;
        }
        else
        {
            return false;
        }
    }    private Boolean Dipo()
    {
        Boolean Valor=true;
        try {
            Statement sx = Consulta.createStatement();
            ResultSet Ca = sx.executeQuery("SELECT id from Usuarios where Usuario='"+usuario.getText()+"'");
            while(Ca.next())
            {
                Valor=false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(verempleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Valor;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verempleado(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirmar;
    private javax.swing.JLabel Diponible;
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> boxpuesto;
    private javax.swing.JPasswordField cocontraseña;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel correcto;
    private javax.swing.JTextField dpi;
    private javax.swing.JLabel dpiregis;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel paneldatos;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
